# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Routers', :path =>'../Routers/'
  pod 'LoginModule', :path =>'../LoginModule/'
  pod 'LoginModuleB', :path =>'../LoginModuleB/'
  pod 'SettingsModule', :path =>'../SettingsModule/'
  
end
